### ISSUE TITLE
s/1.0/1.1

### ISSUE THREAD

**Issue by PhilETaylor** [joomla-framework/http#46]
Should also be changed in the framework 
https://github.com/joomla-framework/http/blob/7ee1ca93a9f86bca5e0570b5c91eff7e207a3a13/src/Transport/Socket.php#L122 and https://github.com/joomla-framework/http/blob/95f46a39dec738f73839e61c035be4fa597e822a/src/Transport/Socket.php#L88

_Originally posted by @PhilETaylor in https://github.com/joomla/joomla-cms/issues/35568#issuecomment-920018536_

**Comment by nibra** [comment]
Thank you!
