### ISSUE TITLE
Remove expired DST Root CA X3 

### ISSUE THREAD

**Issue by wojsmol** [joomla-framework/http#49]
### Steps to reproduce the issue
Update composer/ca-bundle to latest version on 1.0.x branch to remove expired DST Root CA X3 rcoot certificate.

Remove old expired  DST Root CA X3 Let's Encrypt root certificate - see [Old Let’s Encrypt Root Certificate Expiration and OpenSSL 1.0.2](https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/)

### Expected result
HTTPS connections to servers with latests Let's Encrypt certificates from server with openssl version 1.0.2 are working.

### Actual result
HTTPS connections to servers with latests Let's Encrypt certificates from server with openssl version 1.0.2 are NOT working

### System information (as much as possible)
Any server with openssl 1.0.2

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla-framework/http/commit/cb9151b8e3b998c6e1be4203a298d2d0f9a9efa3

Although this bundle isn't actually used by the package - it uses the composer shipped one - we just keep it for b/c

**Comment by wojsmol** [comment]
Composer step is failing on [php 5.4](https://ci.joomla.org/joomla-framework/http/18/4/2) and [php 5.5](https://ci.joomla.org/joomla-framework/http/18/5/2) with curl error 60.
